; generated by PrusaSlicer 2.5.0 on 2023-01-01 at 12:00:00 UTC
; 

; external perimeters extrusion width = 0.45mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.45mm
; top infill extrusion width = 0.40mm
; first layer extrusion width = 0.42mm

; filament used [g] = 12.5
; estimated printing time (normal mode) = 1h 30m
; layer_height = 0.2
; profile_id = MyQualityProfile

G1 X10 Y10 E1
