API_BASE = "http://localhost:3000/api/production"
API_URL = f"{API_BASE}/slicer-hook"
API_PRODUCTS_URL = f"{API_BASE}/products-list"
SECRET_TOKEN = "tu_secreto_super_seguro" 
VERSION = "13.1-Sanity-Check"
