import '@testing-library/jest-dom';

// Mock lucide-react globalmente
jest.mock('lucide-react', () => {
  const React = require('react');
  
  const createMockIcon = (name) => {
    const MockIcon = React.forwardRef((props, ref) => {
      return React.createElement('svg', {
        ...props,
        ref,
        'data-testid': name.toLowerCase(),
        'aria-label': name,
        role: 'img'
      }, name);
    });
    MockIcon.displayName = name;
    return MockIcon;
  };

  return {
    ChevronLeft: createMockIcon('ChevronLeft'),
    ChevronRight: createMockIcon('ChevronRight'),
    Play: createMockIcon('Play'),
    Pause: createMockIcon('Pause'),
    Volume2: createMockIcon('Volume2'),
    VolumeX: createMockIcon('VolumeX'),
    Maximize: createMockIcon('Maximize'),
    Minimize: createMockIcon('Minimize'),
    RotateCcw: createMockIcon('RotateCcw'),
    Download: createMockIcon('Download'),
    Share: createMockIcon('Share'),
    Heart: createMockIcon('Heart'),
    MessageCircle: createMockIcon('MessageCircle'),
    Bookmark: createMockIcon('Bookmark'),
    MoreHorizontal: createMockIcon('MoreHorizontal'),
    Search: createMockIcon('Search'),
    Filter: createMockIcon('Filter'),
    SortAsc: createMockIcon('SortAsc'),
    Grid: createMockIcon('Grid'),
    List: createMockIcon('List'),
    User: createMockIcon('User'),
    Settings: createMockIcon('Settings'),
    LogOut: createMockIcon('LogOut'),
    Menu: createMockIcon('Menu'),
    X: createMockIcon('X'),
    Home: createMockIcon('Home'),
    Map: createMockIcon('Map'),
    Users: createMockIcon('Users'),
    BarChart: createMockIcon('BarChart'),
    Plus: createMockIcon('Plus'),
    Edit: createMockIcon('Edit'),
    Trash: createMockIcon('Trash'),
    Eye: createMockIcon('Eye'),
    EyeOff: createMockIcon('EyeOff'),
    Check: createMockIcon('Check'),
    AlertCircle: createMockIcon('AlertCircle'),
    Info: createMockIcon('Info'),
    Upload: createMockIcon('Upload'),
    Image: createMockIcon('Image'),
    File: createMockIcon('File'),
    Calendar: createMockIcon('Calendar'),
    Clock: createMockIcon('Clock'),
    Mail: createMockIcon('Mail'),
    Phone: createMockIcon('Phone'),
    MapPin: createMockIcon('MapPin'),
    Globe: createMockIcon('Globe'),
    Star: createMockIcon('Star'),
    Tag: createMockIcon('Tag'),
    Folder: createMockIcon('Folder'),
    Copy: createMockIcon('Copy'),
    ExternalLink: createMockIcon('ExternalLink'),
    ArrowRight: createMockIcon('ArrowRight'),
    ArrowLeft: createMockIcon('ArrowLeft'),
    ArrowUp: createMockIcon('ArrowUp'),
    ArrowDown: createMockIcon('ArrowDown'),
    ChevronUp: createMockIcon('ChevronUp'),
    ChevronDown: createMockIcon('ChevronDown'),
    Loader: createMockIcon('Loader'),
    RefreshCw: createMockIcon('RefreshCw'),
    Save: createMockIcon('Save'),
    Send: createMockIcon('Send'),
    Lock: createMockIcon('Lock'),
    Unlock: createMockIcon('Unlock'),
    Shield: createMockIcon('Shield'),
    Key: createMockIcon('Key'),
    Database: createMockIcon('Database'),
    Server: createMockIcon('Server'),
    Cloud: createMockIcon('Cloud'),
    Wifi: createMockIcon('Wifi'),
    WifiOff: createMockIcon('WifiOff'),
    Bluetooth: createMockIcon('Bluetooth'),
    Battery: createMockIcon('Battery'),
    Power: createMockIcon('Power'),
    Monitor: createMockIcon('Monitor'),
    Smartphone: createMockIcon('Smartphone'),
    Tablet: createMockIcon('Tablet'),
    Laptop: createMockIcon('Laptop'),
    HardDrive: createMockIcon('HardDrive'),
    Cpu: createMockIcon('Cpu'),
    MemoryStick: createMockIcon('MemoryStick'),
    Printer: createMockIcon('Printer'),
    Camera: createMockIcon('Camera'),
    Video: createMockIcon('Video'),
    Mic: createMockIcon('Mic'),
    MicOff: createMockIcon('MicOff'),
    Headphones: createMockIcon('Headphones'),
    Speaker: createMockIcon('Speaker'),
    Music: createMockIcon('Music'),
    Radio: createMockIcon('Radio'),
    Tv: createMockIcon('Tv'),
    GameController2: createMockIcon('GameController2'),
    Gamepad: createMockIcon('Gamepad'),
    Joystick: createMockIcon('Joystick'),
    Target: createMockIcon('Target'),
    Crosshair: createMockIcon('Crosshair'),
    Zap: createMockIcon('Zap'),
    Flame: createMockIcon('Flame'),
    Snowflake: createMockIcon('Snowflake'),
    Sun: createMockIcon('Sun'),
    Moon: createMockIcon('Moon'),
    CloudRain: createMockIcon('CloudRain'),
    CloudSnow: createMockIcon('CloudSnow'),
    Wind: createMockIcon('Wind'),
    Thermometer: createMockIcon('Thermometer'),
    Umbrella: createMockIcon('Umbrella'),
    Rainbow: createMockIcon('Rainbow'),
    Sunrise: createMockIcon('Sunrise'),
    Sunset: createMockIcon('Sunset'),
    Mountain: createMockIcon('Mountain'),
    Tree: createMockIcon('Tree'),
    Flower: createMockIcon('Flower'),
    Leaf: createMockIcon('Leaf'),
    Seedling: createMockIcon('Seedling'),
    Bug: createMockIcon('Bug'),
    Fish: createMockIcon('Fish'),
    Bird: createMockIcon('Bird'),
    Cat: createMockIcon('Cat'),
    Dog: createMockIcon('Dog'),
    Rabbit: createMockIcon('Rabbit'),
    Turtle: createMockIcon('Turtle'),
    Elephant: createMockIcon('Elephant'),
    Lion: createMockIcon('Lion'),
    Tiger: createMockIcon('Tiger'),
    Bear: createMockIcon('Bear'),
    Wolf: createMockIcon('Wolf'),
    Fox: createMockIcon('Fox'),
    Deer: createMockIcon('Deer'),
    Horse: createMockIcon('Horse'),
    Cow: createMockIcon('Cow'),
    Pig: createMockIcon('Pig'),
    Sheep: createMockIcon('Sheep'),
    Chicken: createMockIcon('Chicken'),
    Duck: createMockIcon('Duck'),
    Penguin: createMockIcon('Penguin'),
    Owl: createMockIcon('Owl'),
    Eagle: createMockIcon('Eagle'),
    Dove: createMockIcon('Dove'),
    Butterfly: createMockIcon('Butterfly'),
    Bee: createMockIcon('Bee'),
    Spider: createMockIcon('Spider'),
    Snail: createMockIcon('Snail'),
    Octopus: createMockIcon('Octopus'),
    Crab: createMockIcon('Crab'),
    Lobster: createMockIcon('Lobster'),
    Shrimp: createMockIcon('Shrimp'),
    Whale: createMockIcon('Whale'),
    Dolphin: createMockIcon('Dolphin'),
    Shark: createMockIcon('Shark'),
    Jellyfish: createMockIcon('Jellyfish'),
    Starfish: createMockIcon('Starfish'),
    Shell: createMockIcon('Shell'),
    Coral: createMockIcon('Coral'),
    Seaweed: createMockIcon('Seaweed'),
    Anchor: createMockIcon('Anchor'),
    Ship: createMockIcon('Ship'),
    Boat: createMockIcon('Boat'),
    Sailboat: createMockIcon('Sailboat'),
    Submarine: createMockIcon('Submarine'),
    Plane: createMockIcon('Plane'),
    Helicopter: createMockIcon('Helicopter'),
    Rocket: createMockIcon('Rocket'),
    Satellite: createMockIcon('Satellite'),
    Car: createMockIcon('Car'),
    Truck: createMockIcon('Truck'),
    Bus: createMockIcon('Bus'),
    Train: createMockIcon('Train'),
    Bike: createMockIcon('Bike'),
    Motorcycle: createMockIcon('Motorcycle'),
    Scooter: createMockIcon('Scooter'),
    Skateboard: createMockIcon('Skateboard'),
    RollerSkate: createMockIcon('RollerSkate'),
    Shoe: createMockIcon('Shoe'),
    Boot: createMockIcon('Boot'),
    Sandal: createMockIcon('Sandal'),
    Socks: createMockIcon('Socks'),
    Shirt: createMockIcon('Shirt'),
    Pants: createMockIcon('Pants'),
    Dress: createMockIcon('Dress'),
    Skirt: createMockIcon('Skirt'),
    Jacket: createMockIcon('Jacket'),
    Coat: createMockIcon('Coat'),
    Hat: createMockIcon('Hat'),
    Cap: createMockIcon('Cap'),
    Glasses: createMockIcon('Glasses'),
    Sunglasses: createMockIcon('Sunglasses'),
    Watch: createMockIcon('Watch'),
    Ring: createMockIcon('Ring'),
    Necklace: createMockIcon('Necklace'),
    Earrings: createMockIcon('Earrings'),
    Bracelet: createMockIcon('Bracelet'),
    Bag: createMockIcon('Bag'),
    Backpack: createMockIcon('Backpack'),
    Suitcase: createMockIcon('Suitcase'),
    Briefcase: createMockIcon('Briefcase'),
    Wallet: createMockIcon('Wallet'),
    Purse: createMockIcon('Purse'),
    ShoppingBag: createMockIcon('ShoppingBag'),
    ShoppingCart: createMockIcon('ShoppingCart'),
    CreditCard: createMockIcon('CreditCard'),
    Banknote: createMockIcon('Banknote'),
    Coins: createMockIcon('Coins'),
    DollarSign: createMockIcon('DollarSign'),
    Euro: createMockIcon('Euro'),
    Pound: createMockIcon('Pound'),
    Yen: createMockIcon('Yen'),
    Bitcoin: createMockIcon('Bitcoin'),
    TrendingUp: createMockIcon('TrendingUp'),
    TrendingDown: createMockIcon('TrendingDown'),
    PieChart: createMockIcon('PieChart'),
    LineChart: createMockIcon('LineChart'),
    Activity: createMockIcon('Activity'),
    Pulse: createMockIcon('Pulse'),
    Heartbeat: createMockIcon('Heartbeat'),
    Stethoscope: createMockIcon('Stethoscope'),
    Pill: createMockIcon('Pill'),
    Syringe: createMockIcon('Syringe'),
    Bandage: createMockIcon('Bandage'),
    FirstAid: createMockIcon('FirstAid'),
    Hospital: createMockIcon('Hospital'),
    Ambulance: createMockIcon('Ambulance'),
    Cross: createMockIcon('Cross'),
    Plus2: createMockIcon('Plus2'),
    Minus: createMockIcon('Minus'),
    Equal: createMockIcon('Equal'),
    Divide: createMockIcon('Divide'),
    Multiply: createMockIcon('Multiply'),
    Percent: createMockIcon('Percent'),
    Calculator: createMockIcon('Calculator'),
    Ruler: createMockIcon('Ruler'),
    Triangle: createMockIcon('Triangle'),
    Square: createMockIcon('Square'),
    Circle: createMockIcon('Circle'),
    Pentagon: createMockIcon('Pentagon'),
    Hexagon: createMockIcon('Hexagon'),
    Octagon: createMockIcon('Octagon'),
    Diamond: createMockIcon('Diamond'),
    Rhombus: createMockIcon('Rhombus'),
    Parallelogram: createMockIcon('Parallelogram'),
    Trapezoid: createMockIcon('Trapezoid'),
    Cylinder: createMockIcon('Cylinder'),
    Cone: createMockIcon('Cone'),
    Sphere: createMockIcon('Sphere'),
    Cube: createMockIcon('Cube'),
    Pyramid: createMockIcon('Pyramid'),
    Prism: createMockIcon('Prism'),
    Torus: createMockIcon('Torus'),
    Helix: createMockIcon('Helix'),
    Spiral: createMockIcon('Spiral'),
    Wave: createMockIcon('Wave'),
    Sine: createMockIcon('Sine'),
    Cosine: createMockIcon('Cosine'),
    Tangent: createMockIcon('Tangent'),
    Infinity: createMockIcon('Infinity'),
    Pi: createMockIcon('Pi'),
    Sigma: createMockIcon('Sigma'),
    Alpha: createMockIcon('Alpha'),
    Beta: createMockIcon('Beta'),
    Gamma: createMockIcon('Gamma'),
    Delta: createMockIcon('Delta'),
    Epsilon: createMockIcon('Epsilon'),
    Zeta: createMockIcon('Zeta'),
    Eta: createMockIcon('Eta'),
    Theta: createMockIcon('Theta'),
    Iota: createMockIcon('Iota'),
    Kappa: createMockIcon('Kappa'),
    Lambda: createMockIcon('Lambda'),
    Mu: createMockIcon('Mu'),
    Nu: createMockIcon('Nu'),
    Xi: createMockIcon('Xi'),
    Omicron: createMockIcon('Omicron'),
    Rho: createMockIcon('Rho'),
    Tau: createMockIcon('Tau'),
    Upsilon: createMockIcon('Upsilon'),
    Phi: createMockIcon('Phi'),
    Chi: createMockIcon('Chi'),
    Psi: createMockIcon('Psi'),
    Omega: createMockIcon('Omega'),
  };
});

// Mock IntersectionObserver
global.IntersectionObserver = class IntersectionObserver {
  constructor() {}
  observe() {
    return null;
  }
  disconnect() {
    return null;
  }
  unobserve() {
    return null;
  }
};

// Mock ResizeObserver
global.ResizeObserver = class ResizeObserver {
  constructor() {}
  observe() {
    return null;
  }
  disconnect() {
    return null;
  }
  unobserve() {
    return null;
  }
};

// Mock matchMedia
Object.defineProperty(window, 'matchMedia', {
  writable: true,
  value: jest.fn().mockImplementation(query => ({
    matches: false,
    media: query,
    onchange: null,
    addListener: jest.fn(), // deprecated
    removeListener: jest.fn(), // deprecated
    addEventListener: jest.fn(),
    removeEventListener: jest.fn(),
    dispatchEvent: jest.fn(),
  })),
});

// Mock next/router
jest.mock('next/router', () => ({
  useRouter() {
    return {
      route: '/',
      pathname: '/',
      query: {},
      asPath: '/',
      push: jest.fn(),
      pop: jest.fn(),
      reload: jest.fn(),
      back: jest.fn(),
      prefetch: jest.fn().mockResolvedValue(undefined),
      beforePopState: jest.fn(),
      events: {
        on: jest.fn(),
        off: jest.fn(),
        emit: jest.fn(),
      },
    };
  },
}));

// Mock next/navigation
jest.mock('next/navigation', () => ({
  useRouter() {
    return {
      push: jest.fn(),
      replace: jest.fn(),
      prefetch: jest.fn(),
      back: jest.fn(),
      forward: jest.fn(),
      refresh: jest.fn(),
    };
  },
  useSearchParams() {
    return new URLSearchParams();
  },
  usePathname() {
    return '/';
  },
}));